# Generated by Django 6.1 on 2026-09-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], max_length=16)),
                ('secondary_category', models.CharField(blank=True, choices=[('domination', 'Domination'), ('presision', 'Presision'), ('resolve', 'Resolve'), ('sorcery', 'Sorcery')], max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('cooldown', models.IntegerField()),
                ('img_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
