# Generated by Django 6.1 on 2026-09-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='champions',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='champions',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='champions',
            name='name_parsi',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='champions',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='champions',
            name='title_parsi',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='champions',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='champions',
            name='roles',
            field=models.ManyToManyField(related_name='champions', to='champions.championrole'),
        ),
    ]
