# Generated by Django 6.1 on 2026-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_championrole_alter_champions_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='champions',
            new_name='Champion',
        ),
        migrations.AddField(
            model_name='championrole',
            name='code',
            field=models.CharField(default='', max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='championrole',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
