# Generated by Django 6.1 on 2026-09-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0003_rename_champions_champion_championrole_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
