# Generated by Django 6.1 on 2026-09-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0004_champion_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='championrole',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
