# Generated by Django 6.1 on 2026-09-10 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0005_championrole_icon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('passive', 'Passive'), ('first', 'First Ability'), ('second', 'Second Ability'), ('third', 'Third Ability'), ('ultimate', 'Ultimate')], max_length=20)),
                ('name', models.CharField()),
                ('picture', models.URLField()),
                ('video', models.URLField()),
                ('cost', models.CharField()),
                ('cooldown', models.CharField()),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('mana', 'Mana'), ('energy', 'Energy'), ('health', 'Health'), ('none', 'None')], max_length=20)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abiliteis', to='champions.champion')),
            ],
        ),
    ]
