# Generated by Django 6.1 on 2026-09-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0006_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cost',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ability',
            name='picture',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='resource_type',
            field=models.CharField(choices=[('mana', 'Mana'), ('energy', 'Energy'), ('health', 'Health'), ('none', 'None')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ability',
            name='type',
            field=models.CharField(choices=[('passive', 'Passive'), ('first', 'First Ability'), ('second', 'Second Ability'), ('third', 'Third Ability'), ('ultimate', 'Ultimate')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ability',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
