# Generated by Django 6.1 on 2026-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0007_alter_ability_cooldown_alter_ability_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
