# Generated by Django 6.1 on 2026-09-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0008_champion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
