# Generated by Django 6.1 on 2026-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0010_alter_champion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
