# Generated by Django 6.1 on 2026-09-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0011_champion_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cost',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
