# Generated by Django 6.1 on 2026-09-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0012_alter_ability_cooldown_alter_ability_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='champions.champion'),
        ),
    ]
