# Generated by Django 6.1 on 2026-09-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0013_alter_ability_champion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='championrole',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('type', models.ManyToManyField(related_name='items', to='champions.itemtype')),
            ],
        ),
    ]
