# Generated by Django 6.1 on 2026-09-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0014_itemtype_alter_championrole_code_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
    ]
