# Generated by Django 6.1 on 2026-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0015_alter_itemtype_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='stats',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('mid_level', 'Mid level'), ('physical', 'Physical'), ('magical', 'Magical'), ('defensive', 'Defensive'), ('support', 'Support'), ('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], default='', max_length=16),
            preserve_default=False,
        ),
    ]
