# Generated by Django 6.1 on 2026-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0017_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basic', 'Basic'), ('mid_level', 'Mid level'), ('physical', 'Physical'), ('magical', 'Magical'), ('defensive', 'Defensive'), ('support', 'Support'), ('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ManyToManyField(related_name='Items', to='champions.itemtype'),
        ),
    ]
