# Generated by Django 6.1 on 2026-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0018_itemtype_remove_item_type_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ManyToManyField(related_name='items', to='champions.itemtype'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='code',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('mid_tier', 'Mid tier'), ('fighter', 'Fighter'), ('assassin', 'Assassin'), ('marksman', 'Marksman'), ('magic', 'Magic'), ('defense', 'Defense'), ('support', 'Support'), ('basic_boot', 'Basic boot'), ('mid_tier_boot', 'Mid_tier_boot'), ('upgraded', 'Upgraded')], max_length=16),
        ),
    ]
