# Generated by Django 6.1 on 2026-09-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0019_alter_item_type_alter_itemtype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBuildPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_builds', to='champions.item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_paths', to='champions.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
