# Generated by Django 6.1 on 2026-09-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0021_move_items_to_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
