# Generated by Django 6.1 on 2026-09-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0022_champion_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='video_url',
        ),
    ]
